### ISSUE TITLE
NPE in ABM.pde 276

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#23]
```
ArrayList<Node> newPath = new ArrayList<Node>();
```

returns NPE

**Comment by agrignard** [comment]
In order to track this very pleasant bug here is what I found , the 2 bikes network are working, Ped and car are the guilty one. I am thinking to make every agent moving on the bike graph a least for member's week to have something running 

car_1 crash
car_2 crash

bike_1  ok
bike_2 ok

ped_1 crash
ped_2 crash

**Comment by agrignard** [comment]
See #24
